services:
  - type: web
    name: legaleasefile
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: legalease-db
          property: connectionString
      - key: AIRTABLE_API_KEY
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false

databases:
  - name: legalease-db
    databaseName: legalease
    user: legalease