services:
  - type: web
    name: legaleasefile
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
